[bot]
version = "4.11.1"
token = "${BOT_TOKEN}"
initial_extensions = [
    "cogs.locale",
    "cogs.owner",
    "cogs.game_master",
    "cogs.gambling",
    "cogs.adventure",
    "cogs.ranks",
    "cogs.trading",
    "cogs.miscellaneous",
    "cogs.server",
    "cogs.profile",
    "cogs.battles",
    "cogs.help",
    "cogs.vote",
    "cogs.crates",
    "cogs.patreon",
    "cogs.store",
    "cogs.marriage",
    "cogs.guild",
    "cogs.tournament",
    "cogs.classes",
    "cogs.images",
    "cogs.global_events",
    "cogs.raid",
    "cogs.gods",
    "cogs.transaction",
    "cogs.races",
    "cogs.hungergames",
    "cogs.maths",
    "cogs.shard_communication",
    "cogs.alliance",
    "cogs.trivia",
    "cogs.chess",
    "cogs.werewolf",
    "cogs.scheduler",
    "cogs.error_handler",
]
global_prefix = "${BOT_GLOBAL_PREFIX}"
is_beta = true
is_custom = false
global_cooldown = 3
donator_cooldown = 2

[external]
patreon_token = "my secret patreon token"
imgur_token = "my secret imgur token"
okapi_token = "my secret okapi token"
traviapi = "just a secret"
base_url = "https://idlerpg.xyz"
okapi_url = "https://okapi.travitia.xyz"
proxy_url = "http://my.proxy"
proxy_auth = "proxy-auth-key"

[[external.donator_roles]]
id = 1234
tier = "basic"

[database]
postgres_url = "${DATABASE_URL}"
postgres_name = "${POSTGRES_DB}"
postgres_user = "${POSTGRES_USER}"
postgres_password = "${POSTGRES_PASSWORD}"
postgres_host = "${POSTGRES_HOST}"
postgres_port = "${POSTGRES_PORT}"
redis_url = "${REDIS_URL}"
redis_host = "${REDIS_HOST}"
redis_port = "${REDIS_PORT}"
redis_database = "${REDIS_DB}"
redis_password = "${REDIS_PASSWORD}"
redis_shard_announce_channel = "${REDIS_SHARD_ANNOUNCE_CHANNEL}"

[statistics]
topggtoken = "topggtoken"
dbltoken = "dbltoken"
bfdtoken = "bfdtoken"
join_channel = 1234567890
sentry_url = "https://whatever.sentry.url"

[launcher]
additional_shards = 4
shards_per_cluster = 4

[game]
game_masters = [1234567890]
banned_guilds = [1234567890]
support_server_id = 1234567890
raid_channel = 1234567890
gm_log_channel = 1234567890
helpme_channel = 1234567890
official_tournament_channel_id = 1234567890
bot_event_channel = 1234567890
primary_colour = 16759808
member_role = 1234567890
support_team_role = 1234567890

[cities]
    [cities.vopnafjor]
    name = "Vopnafjor"
    thief = true
    raid = true
    trade = true
    adventure = true
    tier = 4

    [cities.medriguen]
    name = "Medriguen"
    thief = false
    raid = true
    trade = true
    adventure = true
    tier = 3

    [cities.sulitere]
    name = "Sulitere"
    thief = true
    raid = true
    trade = true
    adventure = false
    tier = 3

    [cities.mopra]
    name = "Mopra"
    thief = false
    raid = true
    trade = true
    adventure = false
    tier = 2

    [cities.setrond]
    name = "Setrond"
    thief = true
    raid = false
    trade = true
    adventure = false
    tier = 2

    [cities.armeles]
    name = "Armeles"
    thief = false
    raid = false
    trade = true
    adventure = true
    tier = 2

    [cities.weyeowen]
    name = "Weyeowen"
    thief = true
    raid = false
    trade = false
    adventure = false
    tier = 1

    [cities.oltash]
    name = "Oltash"
    thief = false
    raid = false
    trade = true
    adventure = false
    tier = 1

    [cities.kryvansk]
    name = "Kryvansk"
    thief = false
    raid = true
    trade = false
    adventure = false
    tier = 1

    [cities.drutsk]
    name = "Drutsk"
    thief = false
    raid = false
    trade = false
    adventure = true
    tier = 1

[[gods]]
name = "Hello World"
user = 1234567890
description = "I do stuff"
boundary_low = 0.5
boundary_high = 1.5
